stages:
  download:
    cmd: chmod +x bash/parse_pubchem_rdf.sh; ./bash/parse_pubchem_rdf.sh
    deps:
    - bash/parse_pmc.sh
    outs:
    - download/
  process:
    cmd: Rscript R/process.R
    deps:
    - R/process.R
    outs:
    - data/
